//DO NOT modify this file. Bring changes in from Liquid mainline

this.Form = (function() {
  function Form() {}

  Form.FieldTypes = {
    NUMBER: 'integer',
    STRING: 'string',
    CHOICE: 'choice',
    PHOTO: 'photo',
    BOOLEAN: 'boolean',
    SECTION: 'section',
    DATE: 'date',
    TIME: 'time',
    LOCATION: 'location',
    LENGTH: 'length',
    TEMPERATURE: "temperature",
    CALCULATED_SUM: 'calculatedSum',
    CALCULATED_QUOTIENT: 'calculatedQuotient'
  };

  Form.NumericFieldTypes = [Form.FieldTypes.NUMBER, Form.FieldTypes.LENGTH, Form.FieldTypes.TEMPERATURE, Form.FieldTypes.CALCULATED_SUM, Form.FieldTypes.CALCULATED_QUOTIENT];

  return Form;

})();

// ---
// generated by coffee-script 1.9.2
